### ISSUE TITLE
Replace Logstash Forwarder with Filebeat

### ISSUE THREAD

**Issue by elvarb** [wazuh/ossec-wazuh#20]
Since the Logstash Forwarder is no longer in development and has been replaced with Filebeat it is best to replace it.

This is the logstash input config I have

        ## OSSEC-Wazuh filebeat
        beats {
                port => 5045
                type => "ossec-alerts"
                codec => "json"
                tags => "ossec"
        }

**Comment by snaow** [comment]
Hi @elvarb,

You are totally right, we are creating right now Filebeat config files and we are planning on using it in the near future. 
Since Logstash Forwarder is no longer in development looks like Elastic is kind of forcing users to move from Logstash Forwarder to Filebeat and we will do it.

Your config file seems pretty good, I am sure it will be useful to us, thanks!
