### ISSUE TITLE
Feature Request: Pull in GeoIP Changes from DCID

### ISSUE THREAD

**Issue by cdecker22** [wazuh/ossec-wazuh#30]
@dcid has added some great features in the past few months to his own personal fork of OSSEC:
https://github.com/dcid/ossec-hids/blob/master/CHANGELOG

I'm not very savvy with Git, but I was hoping that someone would be willing to take a look as his repository and merge some of his changes.  In particular I'm interested in his support of _different_geoip_ to alert on simultaneous logins for the same user from two separate locations.

Note: If it is inappropriate to submit an Issue rather than learning how to generate the proper Pull Request(s) then please accept my apologies!

**Comment by ddpbsd** [comment]
If it helps @atomicturtle has done the work to get it working with the main OSSEC repo: https://github.com/atomicturtle/ossec-hids/tree/geoip-v2
I imagine it'll be imported into MASTER after 2.9 is released.

**Comment by snaow** [comment]
Hi @cdecker22,

We are currently working on it, we work every day to keep up-to-date Wazuh with ossec-hids and dcid latest commits.
In this case we need to merge those changes within our dynamic fields and ELK integration, I'll update this post as soon as it is done.

Thanks @ddpbsd, we will take a look on that branch, probably like you said will be easy to merge with our fork.

**Comment by vikman90** [comment]
Hi everyone.

We've imported the changes by @dcid and @atomicturtle, and also introduced some changes:

- An internal option to enable or disable the geolocalization data onto JSON output.
- Changed the rule option "different_geoip" for "different_srcgeoip", since this option refers only to the source geolocation.
- This options works also with `<if_matched_group>` in addition to `<if_matched_sid>`.
- Pattern negation with `!`symbol.
- Minor bugs correction. 

In order to compile OSSEC with GeoIP, we need to install the GeoIP library (`libgeoip-dev` deb, or `GeoIP-devel`rpm), and `make` with option `USE_GEOIP=yes`.

The geolocation data appears in the form:

- `US`
- `US / California`

The new rule options are:

1. `<srcgeoip>MATCH</srcgeoip>`, that matches with the source location.
2. `<dstgeoip>MATCH</dstgeoip>`, that matches with the source location.
3. `<different_srcgeoip />`at rules with `<if_matched_sid>` and `<if_matched_group>` options, that matches only if the source location is different.

**Comment by cdecker22** [comment]
@vikman90 : I pulled down the latest/greatest code and I cannot even get the geoip support to work.

It appears to compile without error, and at the end it does say:
…
USE settings:
…
    USE_GEOIP:        yes
…

In internal_options.xml I have the following set:
```
# Output GeoIP data at JSON alerts
analysisd.geoip_jsonout=1
```

```
# Maild display GeoIP data (0=disabled, 1=enabled)
maild.geoip=1

```

In ossec.conf I have the following set:
`    <geoip_db_path>/etc/GeoLiteCity.dat</geoip_db_path>`

`    <use_geoip>yes</use_geoip>`


I'm running ossec in debug mode and I cannot see any references to GeoIP, but I'm never used the GeoIP support before (wasn't worthwhile before--left it up to logstash).

I did notice that if I try to change <geoip_db_path></geoip_db_path> to something random then I'll get an error, so it definitely knows about this parameter.  I also added a rule that included <different_srcgeoip /> and it knew of that parameter as well.

I did notice that if I change the <geoip_db_path> to a file path that doesn't exist and then run ossec-logtest I never receive an error even though it appears that I should.  When I change it to a valid path the logtest never returns any GeoIP data (nor do I see any in alerts.json).

What am I missing?

**Comment by vikman90** [comment]
Please try to specify the GeoIP database with the tag `<geoipdb>` instead of `<geoip_db_path>`.

Best regards.

**Comment by cdecker22** [comment]
@vikman90 : Thank you for responding at all, responding so quickly, and being so helpful.

Changing the tag alone didn't fix the issue.  The instructions I found in the changelog from the OSSEC project said that the path to the GeoIP database should be relative due to chrooting, but I found that I had to provide the full path to the .dat file.

GeoIP look-ups are now working in logtest.  I'll experiment with the rules now.

On a side note, I'd be willing to give back in my own way by helping document these changes.  Is there someone I should be coordinating with to make sure we don't duplicate efforts?

**Comment by vikman90** [comment]
@cdecker22: Thanks for your response. You shall actually enter the absolute path of the database, since it's loaded before do chroot. I didn't realise of it when I read your comment.

Regarding to the documentation, we have a open-source repository at https://github.com/wazuh/wazuh-documentation, whose changes appear at http://documentation.wazuh.com. It's written in RST and the files are in the folder `source`.

In order to compile the sources and preview the changes, you'll need to install Sphinx, but you can view the results more easily just opening the file at GitHub. For example: https://github.com/wazuh/wazuh-documentation/blob/in-progress/source/manage_agents.rst

We'll be very grateful to you if you start writting the documentation about GeoIP. You can just create a new RST file and we'll add it to the index.

If you finally do it, please send us the pull requests to the branch **in-progress**.

I'd like yo remind you that you can use the Wazuh mailing list (https://groups.google.com/forum/#!forum/wazuh) or the Wazuh Slack Channel.

Thank you very much for your interest.
Best Regards!
